Controllers/OrderController.cs
using _10.Data_Access;
using _10.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace _10.Controllers
{
    public class OrderController : Controller
    {
        private ProductRippo _ProductRippo = new ProductRippo();
        private OrderRippo _OrderRippo = new OrderRippo();

        public IActionResult List()
        {
            if (AcountRippo.currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }

            if (AcountRippo.currentuser.user == Models.user.admin)
            {
                ViewBag.Log = "خروج";
                ViewBag.ErAdmin = "ادمین نمیتواند سفارش دهد ";
                return RedirectToAction("ErroAdmin", "Admin");
            }

            ViewBag.Log = "خروج";
            ViewBag.Name = AcountRippo.currentuser.Name;
            decimal? TotalPrice = 0;
            var result = _OrderRippo.GetList();
            ViewBag.Id = AcountRippo.currentuser.Id;
            foreach (var item in result)
            {
            }
            ViewBag.Products= _ProductRippo.GetList();
            return View(result);

        }
        public IActionResult OrderList(int id)
        {
            ViewBag.OrderId=id;
            var result = _OrderRippo.GetList();
            return View(result);
        }

        public IActionResult Delete(int Id)

        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            foreach (var item in _ProductRippo.GetList())
            {
                if (item.Id == Id)
                {

                    item.Number = item.Number + item.Number2;
                    item.Number2 = 0;
                    item.PersonId = null;
                    break;
                }
            }

            return RedirectToAction("List");

        }

        public IActionResult Delete2(int Id)

        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            foreach (var item in _ProductRippo.GetList())
            {
                if (item.Id == Id)
                {

                    item.Number++;
                    item.Number2--;
                    break;
                }
            }

            return RedirectToAction("List");

        }
        public IActionResult AddNewOrder(int Id)
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var currentItem = _OrderRippo.GetList().Last();
            var result = _OrderRippo.GetList();
            var resultProduct = _OrderRippo.GetList();

            _OrderRippo.Add(new Order
            {
                Id = currentItem.Id + 1,
                CustomerId = AcountRippo.currentuser.Id,
                Productid= new List<int> {Id}
            });

            return RedirectToAction("List");



        }
        public IActionResult AddToOrder(int orderId, int productId)
        {
            
            return RedirectToAction("List");

        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using _10.Controllers;
using _10.Models;
using _10.Data_Access;
using static System.Runtime.InteropServices.JavaScript.JSType;
using System.Xml.Linq;
using System.Reflection;

namespace _10.Controllers
{
    public class ProductController : Controller
    {
            private ProductRippo _ProductRippo = new ProductRippo();
        
            public IActionResult List()
            {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }

            var result = _ProductRippo.GetList();
            return View(result);
               
            }
        public IActionResult Search( string search)
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var result = _ProductRippo.GetList();
            if (search != null)
            {
                ViewBag.Search = search;
                result = result.Where(x => x.Name.Contains(search)).ToList();
            }
            else
            {
                ViewBag.Search = "همه موارد";
            }
            return View(result);
        }

        public IActionResult Create()
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            //throw new DivideByZeroException();
            return View();
        }
        public IActionResult Delete(int id)
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var result = _ProductRippo.GetList();
            foreach (var p in result)
            {
                if (p.Id == id)
                {
                    _ProductRippo.Delete(p.Id);
                    return RedirectToAction("AdminActions","Admin");
                }

            }
            return View("Home/Error");
        }

        public IActionResult Action()
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            return View();
        }
     
        [HttpPost]
        public IActionResult Create(Product model)
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var currentItem = _ProductRippo.GetList().Last();
            var result = _ProductRippo.GetList();

             foreach(var n in  result)
            {
                if(n.Name == model.Name)
                {
                    n.Number = n.Number + model.Number;
                    return RedirectToAction("List");
                }
               
            }
                _ProductRippo.Add(new Product
                {
                    Id = currentItem.Id + 1,
                    Name = model.Name,
                    Number = model.Number,
                    Price = model.Price,
                });
            
            return RedirectToAction("List");
        }
        public IActionResult Edit(int id)
        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var entity = _ProductRippo.Get(id);
            return View(entity);
        }
        [HttpPost]
        public IActionResult Edit(int id, string name, int number, decimal price)

        {
            if (AcountRippo.currentuser != null)
            {
                ViewBag.Log = "خروج";
            }
            var result = _ProductRippo.GetList();
            foreach (var n in result)
            {

                if(n.Id == id)
                {
                _ProductRippo.Edite(id, name, number, price);
                return RedirectToAction("List");
                }
            }
            return View("Home/Error");
        }

    }
}

Controllers/UserController.cs
using _10.Data_Access;
using Microsoft.AspNetCore.Mvc;

namespace _10.Controllers
{
    public class UserController : Controller
    {
        private ProductRippo _ProductRippo = new ProductRippo();
        public IActionResult List()
        {
            
            ViewBag.Log = "خروج";
            var result = _ProductRippo.GetList();
            return View(result);
        }
    }
}

Views/Shared/HandleError.cshtml
@{
    ViewBag.Title = "صفحه یافت نشد ";
}
<br />
<br />
<br />
<br />
<br />
<div class =" text-danger bg-warning border border-dark">


<h1 class="text-center text-white ">@ViewBag.ErrorMessage</h1>
<h3 class="mt-5">صفحه یافت نشد یا چنین آدرسی وجود ندارد </h3>
    <a class="nav-link text-white bg-danger border border-dark mt-5 w-25 p-3" asp-area="" asp-controller="Home" asp-action="Index">
    برای بازگشت به صفحه اصلی کلیک کنید 

</a>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _10</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_10.styles.css" asp-append-version="true" />
</head>
<header>
    <body class="bg-secondary">
        <header>
            <nav class=" navbar navbar-expand-lg fixed-top navbar-light  border border-3 text-light bg-dark ">
                <div class="container-fluid justify-content-center justify-content-md-between">

                    <ul class="navbar-nav flex-row">

                        <div class="d-flex">
                            <ul class="d-flex">
                                @if (ViewBag.Log == null)
                                {
                                    <li class="nav-item d-flex bt-5 border border-white">
                                        <form method="post" class="nav-item d-flex bg-warning">
                                            <button class="nav-link text-danger bg-warning border border-dark" asp-area="" asp-controller="Account" asp-action="Login">ورود </button>

                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item d-flex bt-5  border border-white">
                                        <form method="post" class="nav-item d-flex bg-warning">
                                            <button type="submit" asp-controller="Account" asp-action="LogOut" class="bg-warning text-danger"
                                                onclick="return confirm ('جدی جدی از حسابت میری بیرون ؟')">
                                                @ViewBag.Log
                                            </button>
                                        </form>
                                    </li>

                                }
                                <li class="nav-item d-flex">
                                    <a class="nav-link text-danger bg-warning border border-dark" asp-area="" asp-controller="Home" asp-action="Index">صفحه اصلی</a>
                                </li>




                                <li class="nav-item d-flex">
                                    @if (ViewBag.Log == null)
                                    {
                                        <a class="nav-link text-danger bg-warning border border-dark" asp-area="" asp-controller="Product" asp-action="List">نمایش کالاها</a>
                                    }
                                    else
                                    {
                                        <a class="nav-link text-danger bg-warning border border-dark" asp-area="" asp-controller="User" asp-action="List">لیست کالاها</a>
                                    }
                                </li>
                                <li class="nav-item d-flex">
                                    <form>
                                        @if (ViewBag.Log == null)
                                        {
                                            <Button class="nav-link text-danger bg-warning border border-dark"
                                                asp-area="" asp-controller="Order" asp-action="List"
                                                onclick="return confirm ('اول باید وارد حسابت شی جیگر  :) ')">
                                                مشاهده سبد خرید
                                            </Button>
                                        }
                                        else
                                        {
                                            <Button class="nav-link text-danger bg-warning border border-dark" asp-area="" asp-controller="Order" asp-action="List">مشاهده سبد خرید </Button>

                                        }


                                    </form>
                                </li>

                            </ul>
                        </div>


                    </ul>
                    <!-- Avatar -->

                    <div class="bg-warning text-danger">
                    </div>

                    <div class="d-flex my-2 my-sm-0">

                        <!-- Search form -->
                        <form method="post">
                            <div class="bt-5">
                                <input type="text" name="search" class="bg-secondary" placeholder="@ViewBag.Search" />
                                <button type="submit" asp-controller="Product" asp-action="Search" class="bg-warning text-danger">جست و جو</button>
                            </div>
                        </form>
                       
                    </div>
                </div>
            </nav>

        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</header>
</html>